# This is a basic workflow to help you get started with Actions

name: Puppetfile checks 

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

env:
  GITHUB_USER: ${{ secrets.PUPPET_REPO_USER }}
  GITHUB_TOKEN: ${{ secrets.PUPPET_REPO_USER_TOKEN }}

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppetfile:
    name: puppetfile 
    uses: logicminds/gha-puppet/.github/workflows/puppetfile.yml@puppetfile 

